steps:
* Terminal Commands
    * pip install numpy(for anaconda: conda install numpy )
    * python -m pip install ipykernel(for conda : conda install ipykernel)
* for jupyter notebook:
    * its preinstalled in conda base env.
    * for normal installation use "pip install notebook"




* Make a new file with .ipynb extention and start coding.

In [68]:
#make a small list on numbers
numbers = [1,2,3,4,5,6,7,8,9,10]

In [69]:
#import numpy
import numpy as np

In [70]:
#making the numbers list into an numpy array
numbers_np = np.array(numbers)

In [71]:
#calling numbers_np
numbers_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
#list of three lists
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
#this is a unclear representation of the 2d lists
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [73]:
#for clear 2d represatation of the 2d lists
list_of_lists_np = np.array(list_of_lists)
list_of_lists_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
#creating a list with numpy using numpy arange
np.arange(1,11)
#here the two params are start and end+1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
#we can also add another param to numpy arange
np.arange(1,11,2)
#here the third param is the step size

array([1, 3, 5, 7, 9])

In [76]:
#generating 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
#two dimentional zeros by adding a tuple of two int inside the np.zeros
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
#simillerly we can generate 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
#and also ones with a tuple of two int which makes a 3x3 matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.linspace(0,10,5)
#here the first param is the start of the range
#the second param is the end of the range
#the third param is the number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [135]:
#indentity matrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [136]:
#random numbers
np.random.rand(5)
#this generates 5 random numbers between 0 and 1


array([0.24228113, 0.72229537, 0.26491803, 0.92589608, 0.62376406])

In [137]:
#for 2d matrix
np.random.rand(3,3)

array([[0.56521953, 0.00678138, 0.00212445],
       [0.54980317, 0.07272112, 0.63945687],
       [0.20713626, 0.71874069, 0.25854002]])

In [138]:
#random normal distribution
np.random.randn(10)
#this generates 3 random numbers from a normal distribution


array([-0.67478945,  2.19131476, -0.48127578,  1.09877679,  0.20960252,
        1.36156207,  1.30403798,  0.49581915,  0.50686659, -0.07346993])

In [139]:
#for 2d matrix
np.random.randn(3,3)

array([[-0.32541743,  3.00923126, -0.0391555 ],
       [ 0.25344701,  0.96841311, -0.73585994],
       [-0.73879424, -0.16292205,  1.97334136]])

In [86]:
np.random.randint(1,100,10)
#this generates 10 random numbers between 1 and 100-1

array([44, 42, 24, 28, 42, 27, 71, 19, 68, 96])

In [87]:
#making a array of 20 int random numbers between 1 and 100
np_random_int = np.random.randint(1,100,20)

In [88]:
np_random_int

array([82, 63, 19, 19, 87, 72, 23, 81, 42, 20, 64, 35,  9, 35, 88, 18, 97,
       55, 75, 91])

In [89]:
#reshaping the array
np_random_int.reshape(4,5)

array([[82, 63, 19, 19, 87],
       [72, 23, 81, 42, 20],
       [64, 35,  9, 35, 88],
       [18, 97, 55, 75, 91]])

In [90]:
#finding max
np.max(np_random_int)
#or
np_random_int.max()

97

In [91]:
#finding min
np.min(np_random_int)
#or
np_random_int.min()


9

In [92]:
#index of max
np.argmax(np_random_int)
#or
np_random_int.argmax()

16

In [93]:
#index of min
np.argmin(np_random_int)
#or
np_random_int.argmin()


12

In [94]:
#shape of array
np_random_int.shape

(20,)

In [95]:
#reshaping and then chekcing shape
new_np_random_int = np_random_int.reshape(5,4)
new_np_random_int.shape

(5, 4)

In [96]:
#checking datatype
np_random_int.dtype

dtype('int32')

In [97]:
#importing randint function from numpy
from numpy.random import randint

In [98]:
#generating 10 random numbers between 1 and 100
randint(1,100,10)

array([86, 60, 82, 78, 37, 99, 85, 76, 98, 24])

# Numpy Indexing

In [99]:
#array of 0 to 10
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
#value of index 8
arr[8]

8

In [101]:
#list of items from 1 to 5
arr[1:6]

array([1, 2, 3, 4, 5])

In [102]:
#everything to index 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [103]:
#evrything from index 6 to end
arr[6:]


array([ 6,  7,  8,  9, 10])

In [104]:
#setting index 0 to 5 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [105]:
#make another array from 0 to 20
arr2 = np.arange(0,21)
#broadcasting the array of 0 to 10 in another variable
arr3 = arr2[:10]
arr3


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
#changing the value of arr3 from index 0 to 5 into 99
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [107]:
#printing the arr2
arr2
#which changed the value of arr2 from index 0 to 5 into 99
#which means arr3 is a view of arr2 and not a copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [108]:
#resetting the arr2 variable
arr2 = np.arange(0,21)
#now to copy a part of arr2 into arr3
arr3 = arr2[:10].copy()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
#now changing the value of arr3 from index 0 to 5 into 99 and printing
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [110]:
print(arr2)
#arr2 is not changed but arr3 is changed
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99 99 99 99 99  5  6  7  8  9]


In [111]:
#making a 2d array
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [112]:
#there are two ways to grab a value from a 2d array
print(arr2d[0,1])
#single brackets with a comma
print(arr2d[0][1])
#double brackets

10
10


In [113]:
#we can also slice the 2d array with single brackets
print(arr2d[0:2,1:3])
#and also with double brackets
print(arr2d[0:2,1:3])

[[10 15]
 [25 30]]
[[10 15]
 [25 30]]


In [114]:
#but to simplify we can grab the first 2 row
print(arr2d[0:2])

[[ 5 10 15]
 [20 25 30]]


In [115]:
#to grab the last 2 row
print(arr2d[1:])

[[20 25 30]
 [35 40 45]]


In [116]:
#to grab the first 2 rows and first 2 columns
print(arr2d[0:2,0:2])
#with double brackets
print(arr2d[0:2][0:2])


[[ 5 10]
 [20 25]]
[[ 5 10 15]
 [20 25 30]]


In [117]:
#to grab the first row and last 2 columns
print(arr2d[0:1,2:])

[[15]]


In [118]:
#create a new array from 1 to 20
arr = np.arange(1,21)
#now to find all the elements less then 5 
arr[arr<5]

array([1, 2, 3, 4])

In [119]:
#to simplify
arr < 5
#returns a boolean array

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [120]:
#then when we use this boolean array we can use it to select the elements
arr[arr<5]

array([1, 2, 3, 4])

In [121]:
#now we can reshape a single array into a 2d array
#lets start by making a 1d array from 1 to 50
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [122]:
#now reshaping the array
arr = arr.reshape(5,10)
#but we have to make sure that the shape is correct before reshaping
#otherwise we will get an error, here we have 5 rows and 10 columns
#which means 5*10 = 50 
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

# Numpy Operations

In [123]:
#create a new array from 0 to 10
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
#addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [125]:
#substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [126]:
# multiplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [127]:
#add,sub and mul with 100 and print that
print(arr + 100)
print(arr - 100)
print(arr * 100)


[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[   0  100  200  300  400  500  600  700  800  900 1000]


In [128]:
#dividing 0 by 1
0/1

0.0

In [129]:
#we get an error
#but in numpy if we do this let see what happens
arr/arr
#we get 

C:\Users\Rishat\AppData\Local\Temp\ipykernel_11564\2630066039.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [130]:
#expomnent
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [131]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [132]:
#exponential
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [133]:
#sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [134]:
#log
np.log(arr)

C:\Users\Rishat\AppData\Local\Temp\ipykernel_11564\866679089.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

universal function list __[Scipy](https://numpy.org/doc/stable/reference/ufuncs.html)__

# Greate JOB!!!!