steps:
* Terminal Commands
    * pip install numpy(for anaconda: conda install numpy )
    * python -m pip install ipykernel(for conda : conda install ipykernel)
* for jupyter notebook:
    * its preinstalled in conda base env.
    * for normal installation use "pip install notebook"




* Make a new file with .ipynb extention and start coding.

In [1]:
#make a small list on numbers
numbers = [1,2,3,4,5,6,7,8,9,10]

In [2]:
#import numpy
import numpy as np

In [3]:
#making the numbers list into an numpy array
numbers_np = np.array(numbers)

In [4]:
#calling numbers_np
numbers_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#list of three lists
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
#this is a unclear representation of the 2d lists
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
#for clear 2d represatation of the 2d lists
list_of_lists_np = np.array(list_of_lists)
list_of_lists_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#creating a list with numpy using numpy arange
np.arange(1,11)
#here the two params are start and end+1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#we can also add another param to numpy arange
np.arange(1,11,2)
#here the third param is the step size

array([1, 3, 5, 7, 9])

In [11]:
#generating 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#two dimentional zeros by adding a tuple of two int inside the np.zeros
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#simillerly we can generate 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#and also ones with a tuple of two int which makes a 3x3 matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0,10,5)
#here the first param is the start of the range
#the second param is the end of the range
#the third param is the number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
#indentity matrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#random numbers
np.random.rand(5)
#this generates 5 random numbers between 0 and 1


array([0.64306139, 0.6058687 , 0.77711374, 0.56037192, 0.94950558])

In [27]:
#for 2d matrix
np.random.rand(3,3)

array([[0.43614728, 0.05267249, 0.53143268],
       [0.57589712, 0.59509446, 0.8247927 ],
       [0.75850668, 0.79438583, 0.0547098 ]])

In [46]:
#random normal distribution
np.random.randn(10)
#this generates 3 random numbers from a normal distribution


array([ 0.41062046,  0.26613832,  0.10807361,  0.40048468, -0.52159467,
        1.23629863,  1.6741008 ,  1.14289778, -1.37005981,  0.39101693])

In [47]:
#for 2d matrix
np.random.randn(3,3)

array([[ 1.16691816,  0.96164044,  0.8747686 ],
       [ 0.77625774, -1.25456957,  0.73328409],
       [-1.77656927, -0.13026286,  0.57352037]])

In [48]:
np.random.randint(1,100,10)
#this generates 10 random numbers between 1 and 100-1

array([33, 68, 14, 75, 28, 47, 58, 17, 14, 92])

In [49]:
#making a array of 20 int random numbers between 1 and 100
np_random_int = np.random.randint(1,100,20)

In [50]:
np_random_int

array([ 6, 11, 78, 41, 29, 59, 92, 73, 73, 74, 30, 37, 23, 52, 11, 26, 91,
       20, 51, 23])

In [52]:
#reshaping the array
np_random_int.reshape(4,5)

array([[ 6, 11, 78, 41, 29],
       [59, 92, 73, 73, 74],
       [30, 37, 23, 52, 11],
       [26, 91, 20, 51, 23]])

In [53]:
#finding max
np.max(np_random_int)
#or
np_random_int.max()

92

In [55]:
#finding min
np.min(np_random_int)
#or
np_random_int.min()


6

In [56]:
#index of max
np.argmax(np_random_int)
#or
np_random_int.argmax()

6

In [57]:
#index of min
np.argmin(np_random_int)
#or
np_random_int.argmin()


0

In [58]:
#shape of array
np_random_int.shape

(20,)

In [59]:
#reshaping and then chekcing shape
new_np_random_int = np_random_int.reshape(5,4)
new_np_random_int.shape

(5, 4)

In [61]:
#checking datatype
np_random_int.dtype

dtype('int32')

In [63]:
#importing randint function from numpy
from numpy.random import randint

In [64]:
#generating 10 random numbers between 1 and 100
randint(1,100,10)

array([73,  8, 44, 39, 79, 52, 79, 39, 82, 20])