steps:
* Terminal Commands
    * pip install numpy(for anaconda: conda install numpy )
    * python -m pip install ipykernel(for conda : conda install ipykernel)
* for jupyter notebook:
    * its preinstalled in conda base env.
    * for normal installation use "pip install notebook"




* Make a new file with .ipynb extention and start coding.

In [1]:
#make a small list on numbers
numbers = [1,2,3,4,5,6,7,8,9,10]

In [2]:
#import numpy
import numpy as np

In [3]:
#making the numbers list into an numpy array
numbers_np = np.array(numbers)

In [4]:
#calling numbers_np
numbers_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#list of three lists
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
#this is a unclear representation of the 2d lists
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
#for clear 2d represatation of the 2d lists
list_of_lists_np = np.array(list_of_lists)
list_of_lists_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#creating a list with numpy using numpy arange
np.arange(1,11)
#here the two params are start and end+1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
#we can also add another param to numpy arange
np.arange(1,11,2)
#here the third param is the step size

array([1, 3, 5, 7, 9])

In [9]:
#generating 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#two dimentional zeros by adding a tuple of two int inside the np.zeros
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#simillerly we can generate 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
#and also ones with a tuple of two int which makes a 3x3 matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,10,5)
#here the first param is the start of the range
#the second param is the end of the range
#the third param is the number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
#indentity matrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
#random numbers
np.random.rand(5)
#this generates 5 random numbers between 0 and 1


array([0.38360167, 0.25952157, 0.60461146, 0.84943397, 0.48631253])

In [16]:
#for 2d matrix
np.random.rand(3,3)

array([[0.83319377, 0.71002329, 0.85737372],
       [0.25425881, 0.21965294, 0.95871699],
       [0.99635998, 0.12977666, 0.59957181]])

In [17]:
#random normal distribution
np.random.randn(10)
#this generates 3 random numbers from a normal distribution


array([ 0.68691941, -0.62515278, -1.12226309,  0.09222647,  0.23791302,
        0.96901644, -0.38553411,  1.04047693, -0.08537828, -1.74242455])

In [18]:
#for 2d matrix
np.random.randn(3,3)

array([[-0.27491846,  0.69213855, -1.15810324],
       [-0.21649054,  0.8649154 , -0.25196287],
       [-0.84171826,  1.17946922, -1.90554901]])

In [19]:
np.random.randint(1,100,10)
#this generates 10 random numbers between 1 and 100-1

array([82, 34, 86,  9, 36,  3, 98, 85, 43, 96])

In [20]:
#making a array of 20 int random numbers between 1 and 100
np_random_int = np.random.randint(1,100,20)

In [21]:
np_random_int

array([77, 40, 99, 60, 10, 74, 92, 94, 83, 43, 33, 63, 41, 75,  9, 34, 42,
       72, 74, 44])

In [22]:
#reshaping the array
np_random_int.reshape(4,5)

array([[77, 40, 99, 60, 10],
       [74, 92, 94, 83, 43],
       [33, 63, 41, 75,  9],
       [34, 42, 72, 74, 44]])

In [23]:
#finding max
np.max(np_random_int)
#or
np_random_int.max()

99

In [24]:
#finding min
np.min(np_random_int)
#or
np_random_int.min()


9

In [25]:
#index of max
np.argmax(np_random_int)
#or
np_random_int.argmax()

2

In [26]:
#index of min
np.argmin(np_random_int)
#or
np_random_int.argmin()


14

In [27]:
#shape of array
np_random_int.shape

(20,)

In [28]:
#reshaping and then chekcing shape
new_np_random_int = np_random_int.reshape(5,4)
new_np_random_int.shape

(5, 4)

In [29]:
#checking datatype
np_random_int.dtype

dtype('int32')

In [30]:
#importing randint function from numpy
from numpy.random import randint

In [31]:
#generating 10 random numbers between 1 and 100
randint(1,100,10)

array([12, 52, 98, 10, 95, 83,  7, 14,  1, 43])

# Numpy Indexing

In [32]:
#array of 0 to 10
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
#value of index 8
arr[8]

8

In [34]:
#list of items from 1 to 5
arr[1:6]

array([1, 2, 3, 4, 5])

In [35]:
#everything to index 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [36]:
#evrything from index 6 to end
arr[6:]


array([ 6,  7,  8,  9, 10])

In [37]:
#setting index 0 to 5 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
#make another array from 0 to 20
arr2 = np.arange(0,21)
#broadcasting the array of 0 to 10 in another variable
arr3 = arr2[:10]
arr3


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#changing the value of arr3 from index 0 to 5 into 99
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [40]:
#printing the arr2
arr2
#which changed the value of arr2 from index 0 to 5 into 99
#which means arr3 is a view of arr2 and not a copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [41]:
#resetting the arr2 variable
arr2 = np.arange(0,21)
#now to copy a part of arr2 into arr3
arr3 = arr2[:10].copy()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#now changing the value of arr3 from index 0 to 5 into 99 and printing
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [43]:
print(arr2)
#arr2 is not changed but arr3 is changed
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99 99 99 99 99  5  6  7  8  9]


In [44]:
#making a 2d array
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
#there are two ways to grab a value from a 2d array
print(arr2d[0,1])
#single brackets with a comma
print(arr2d[0][1])
#double brackets

10
10


In [68]:
#we can also slice the 2d array with single brackets
print(arr2d[0:2,1:3])
#and also with double brackets
print(arr2d[0:2,1:3])

[[10 15]
 [25 30]]
[[10 15]
 [25 30]]


In [47]:
#but to simplify we can grab the first 2 row
print(arr2d[0:2])

[[ 5 10 15]
 [20 25 30]]


In [48]:
#to grab the last 2 row
print(arr2d[1:])

[[20 25 30]
 [35 40 45]]


In [49]:
#to grab the first 2 rows and first 2 columns
print(arr2d[0:2,0:2])
#with double brackets
print(arr2d[0:2][0:2])


[[ 5 10]
 [20 25]]
[[ 5 10 15]
 [20 25 30]]


In [50]:
#to grab the first row and last 2 columns
print(arr2d[0:1,2:])

[[15]]


In [51]:
#create a new array from 1 to 20
arr = np.arange(1,21)
#now to find all the elements less then 5 
arr[arr<5]

array([1, 2, 3, 4])

In [52]:
#to simplify
arr < 5
#returns a boolean array

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [53]:
#then when we use this boolean array we can use it to select the elements
arr[arr<5]

array([1, 2, 3, 4])

In [54]:
#now we can reshape a single array into a 2d array
#lets start by making a 1d array from 1 to 50
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [55]:
#now reshaping the array
arr = arr.reshape(5,10)
#but we have to make sure that the shape is correct before reshaping
#otherwise we will get an error, here we have 5 rows and 10 columns
#which means 5*10 = 50 
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

# Numpy Operations

In [56]:
#create a new array from 0 to 10
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
#addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
#substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
# multiplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [60]:
#add,sub and mul with 100 and print that
print(arr + 100)
print(arr - 100)
print(arr * 100)


[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[   0  100  200  300  400  500  600  700  800  900 1000]


In [61]:
#dividing 0 by 1
0/1

0.0

In [62]:
#we get an error
#but in numpy if we do this let see what happens
arr/arr
#we get 

C:\Users\Rishat\AppData\Local\Temp\ipykernel_14784\1107493224.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [63]:
#expomnent
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [64]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [65]:
#exponential
np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [66]:
#sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [67]:
#log
np.log(arr)

C:\Users\Rishat\AppData\Local\Temp\ipykernel_14784\2388929641.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

universal function list __[Scipy](https://numpy.org/doc/stable/reference/ufuncs.html)__

# Greate JOB!!!!