steps:
* Terminal Commands
    * pip install numpy(for anaconda: conda install numpy )
    * python -m pip install ipykernel(for conda : conda install ipykernel)
* for jupyter notebook:
    * its preinstalled in conda base env.
    * for normal installation use "pip install notebook"




* Make a new file with .ipynb extention and start coding.

In [3]:
#make a small list on numbers
numbers = [1,2,3,4,5,6,7,8,9,10]

In [4]:
#import numpy
import numpy as np

In [5]:
#making the numbers list into an numpy array
numbers_np = np.array(numbers)

In [6]:
#calling numbers_np
numbers_np

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#list of three lists
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
#this is a unclear representation of the 2d lists
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
#for clear 2d represatation of the 2d lists
list_of_lists_np = np.array(list_of_lists)
list_of_lists_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#creating a list with numpy using numpy arange
np.arange(1,11)
#here the two params are start and end+1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#we can also add another param to numpy arange
np.arange(1,11,2)
#here the third param is the step size

array([1, 3, 5, 7, 9])

In [11]:
#generating 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#two dimentional zeros by adding a tuple of two int inside the np.zeros
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#simillerly we can generate 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#and also ones with a tuple of two int which makes a 3x3 matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(0,10,5)
#here the first param is the start of the range
#the second param is the end of the range
#the third param is the number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
#indentity matrix
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#random numbers
np.random.rand(5)
#this generates 5 random numbers between 0 and 1


array([0.6978452 , 0.46894977, 0.63546872, 0.3476143 , 0.36193006])

In [18]:
#for 2d matrix
np.random.rand(3,3)

array([[0.70123636, 0.11085975, 0.22183834],
       [0.95540943, 0.49966229, 0.26869271],
       [0.94829183, 0.86518564, 0.36307852]])

In [19]:
#random normal distribution
np.random.randn(10)
#this generates 3 random numbers from a normal distribution


array([-1.5968466 , -0.51908737, -0.26977233,  0.41064599, -0.87463933,
        1.62406054, -0.43798939,  0.46264529,  0.59948184, -0.08260767])

In [20]:
#for 2d matrix
np.random.randn(3,3)

array([[ 2.82214126,  1.23872657,  1.30654854],
       [ 1.85732169, -1.48568342, -0.09434939],
       [-0.43944189, -0.77237566, -0.87819792]])

In [21]:
np.random.randint(1,100,10)
#this generates 10 random numbers between 1 and 100-1

array([34, 41, 12, 21, 77, 56, 52, 36, 52,  2])

In [22]:
#making a array of 20 int random numbers between 1 and 100
np_random_int = np.random.randint(1,100,20)

In [23]:
np_random_int

array([60, 21, 74,  8, 10, 25, 35, 92, 15, 44, 58, 86, 31, 73, 24, 74, 83,
       39, 18, 46])

In [24]:
#reshaping the array
np_random_int.reshape(4,5)

array([[60, 21, 74,  8, 10],
       [25, 35, 92, 15, 44],
       [58, 86, 31, 73, 24],
       [74, 83, 39, 18, 46]])

In [25]:
#finding max
np.max(np_random_int)
#or
np_random_int.max()

92

In [26]:
#finding min
np.min(np_random_int)
#or
np_random_int.min()


8

In [27]:
#index of max
np.argmax(np_random_int)
#or
np_random_int.argmax()

7

In [28]:
#index of min
np.argmin(np_random_int)
#or
np_random_int.argmin()


3

In [29]:
#shape of array
np_random_int.shape

(20,)

In [30]:
#reshaping and then chekcing shape
new_np_random_int = np_random_int.reshape(5,4)
new_np_random_int.shape

(5, 4)

In [31]:
#checking datatype
np_random_int.dtype

dtype('int32')

In [32]:
#importing randint function from numpy
from numpy.random import randint

In [33]:
#generating 10 random numbers between 1 and 100
randint(1,100,10)

array([42, 34, 98,  4, 20, 17,  9, 63, 47, 22])

In [34]:
#array of 0 to 10
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#value of index 8
arr[8]

8

In [36]:
#list of items from 1 to 5
arr[1:6]

array([1, 2, 3, 4, 5])

In [37]:
#everything to index 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [38]:
#evrything from index 6 to end
arr[6:]


array([ 6,  7,  8,  9, 10])

In [39]:
#setting index 0 to 5 to 100
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
#make another array from 0 to 20
arr2 = np.arange(0,21)
#broadcasting the array of 0 to 10 in another variable
arr3 = arr2[:10]
arr3


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#changing the value of arr3 from index 0 to 5 into 99
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [42]:
#printing the arr2
arr2
#which changed the value of arr2 from index 0 to 5 into 99
#which means arr3 is a view of arr2 and not a copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [44]:
#resetting the arr2 variable
arr2 = np.arange(0,21)
#now to copy a part of arr2 into arr3
arr3 = arr2[:10].copy()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#now changing the value of arr3 from index 0 to 5 into 99 and printing
arr3[:5] = 99
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [48]:
print(arr2)
#arr2 is not changed but arr3 is changed
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99 99 99 99 99  5  6  7  8  9]


In [49]:
#making a 2d array
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
#there are two ways to grab a value from a 2d array
print(arr2d[0,1])
#single brackets with a comma
print(arr2d[0][1])
#double brackets

10
10


In [52]:
#we can also slice the 2d array with single brackets
print(arr2d[0:2,1:3])
#and also with double brackets
print(arr2d[0:2,1:3])

[[10 15]
 [25 30]]
[[10 15]
 [25 30]]


In [53]:
#but to simplify we can grab the first 2 row
print(arr2d[0:2])

[[ 5 10 15]
 [20 25 30]]


In [54]:
#to grab the last 2 row
print(arr2d[1:])

[[20 25 30]
 [35 40 45]]


In [55]:
#to grab the first 2 rows and first 2 columns
print(arr2d[0:2,0:2])
#with double brackets
print(arr2d[0:2][0:2])


[[ 5 10]
 [20 25]]
[[ 5 10 15]
 [20 25 30]]


In [64]:
#to grab the first row and last 2 columns
print(arr2d[0:1,2:])

[[15]]


In [65]:
#create a new array from 1 to 20
arr = np.arange(1,21)
#now to find all the elements less then 5 
arr[arr<5]

array([1, 2, 3, 4])

In [66]:
#to simplify
arr < 5
#returns a boolean array

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [67]:
#then when we use this boolean array we can use it to select the elements
arr[arr<5]

array([1, 2, 3, 4])

In [68]:
#now we can reshape a single array into a 2d array
#lets start by making a 1d array from 1 to 50
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [70]:
#now reshaping the array
arr = arr.reshape(5,10)
#but we have to make sure that the shape is correct before reshaping
#otherwise we will get an error, here we have 5 rows and 10 columns
#which means 5*10 = 50 
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])